services:
    wix_framework.instance_decoder:
        class: Wix\FrameworkComponent\InstanceDecoder
        arguments: [%wix_framework.config.keys%]

    wix_framework.controller.listener:
        class: Wix\FrameworkBundle\EventListener\ControllerListener
        arguments: [@annotation_reader, @wix_framework.instance_decoder]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    wix_framework.debug_toolbar:
        class: Wix\FrameworkBundle\DataCollector\DebugToolbar
        arguments: [@wix_framework.instance_decoder, %wix_framework.config.keys%]
        tags:
            - { name: data_collector, template: "WixFrameworkBundle:Collector:toolbar.html.twig", id: "wix_framework_debug_toolbar" }

    wix_framework.twig:
        class: Wix\FrameworkBundle\Twig\Extension\WixExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }